<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>

<div data-block="minicart" class="minicart-wrapper">
    <a class="action showcart" href="#showcart" ontouchstart=""
       data-bind="scope: 'minicart_content'">
        <span class="text"><?= $block->escapeHtml(__('My Cart')) ?></span>
        <span class="counter qty empty"
              data-bind="css: { empty: !summaryCount() }">
            <span class="counter-number"><!-- ko text: summaryCount -->0<!-- /ko --></span>
        </span>
    </a>
    <div class="block-minicart"
         data-mage-init='{"Magento_Ui/js/modal/modal":{
            "type": "slide",
            "title": "<?= $block->escapeHtmlAttr(__('My Cart')) ?>",
            "trigger": ".showcart",
            "buttons": []}}'
        data-bind="scope: 'minicart_content'">
            <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
    <script>
        window.checkout = <?= /* @noEscape */ $block->getSerializedConfig() ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
        }
    }
    </script>
</div>


