<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**  @var $block \Magento\Checkout\Block\Cart */
?>
<div class="cart-empty">
    <?= $block->getChildHtml('checkout_cart_empty_widget') ?>
    <p><?= $block->escapeHtml(__('You have no items in your shopping cart.')) ?></p>
    <p><a href="/webbutik"><?= $block->escapeHtml(
        __('Continue Shopping')
    ) ?></a>
    </p>
    <?= $block->getChildHtml('shopping.cart.table.after') ?>
</div>
