<?php

// @codingStandardsIgnoreFile

/**
 * @see \Magento\Checkout\Block\Cart\Totals
 */
?>
<?php if ($block->getTotals()):
    $tax = '';
    foreach ($this->getTotals() as $total) {
        if ($total->getArea() == 'footer') {
            continue;
        }
        if ($total->getCode() == 'tax') {
            $tax = $block->renderTotal($total);
        } else {
            echo $block->renderTotal($total);
        }
    }
    echo str_replace(
        '</th>',
        ' ' . $block->escapeHtml(__('Incl. Tax')) . '</th>',
        $block->renderTotals('footer')
    ); 
    echo str_replace('Moms', 'varav moms', $tax);
endif; ?>
