<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php
$qtyValidators = $block->getQuantityValidators();
$minAllowed = 0;
$maxAllowed = 0;
$qtyIncrements = 1;

if (isset($qtyValidators['validate-item-quantity']['minAllowed'])) {
    $params = $qtyValidators['validate-item-quantity'];
    $minAllowed = $params['minAllowed'];

    if (isset($params['maxAllowed'])) {
        $maxAllowed = $params['maxAllowed'];
    }
    if (isset($params['qtyIncrements'])) {
        $qtyIncrements = $params['qtyIncrements'];
    }
}
?>
<?php if ($_product->isSaleable()) :?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       min="<?= $minAllowed * 1 ?>" 
                       <?php if ($maxAllowed * 1 > 0) :?>max="<?= $maxAllowed * 1 ?>"
                       <?php endif; ?>step="<?= $qtyIncrements * 1 ?>"
                       value="<?= $block->getProductDefaultQty() * 1 ?>"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty"
                       />
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/catalog-add-to-cart": {}
        }
    }
</script>
