<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
    $_helper = $this->helper(Magento\Catalog\Helper\Output::class);
    $_product = $block->getProduct();
    $_additional = $block->getAdditionalData() ?? [];
    //$weight = $_product->getData('weight') ?? 0;
    $weight = 0;
?>
<?php if ($_additional || $weight >= 0.05) :?>
    <div class="additional-attributes-wrapper table-wrapper">
        <table class="data table additional-attributes" id="product-attribute-specs-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('More Information')) ?></caption>
            <tbody>
            <?php foreach ($_additional as $_data) :?>
                <tr>
                    <th class="col label" scope="row"><?= $block->escapeHtml($_data['label']) ?></th>
                    <td class="col data" data-th="<?= $block->escapeHtmlAttr($_data['label']) ?>"><?= /* @noEscape */ $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?>
                    <?php if ($_data['code'] === 'kruka_hojd') :?>
                        <meta itemprop="height" content="<?= $block->escapeHtmlAttr(str_replace(',', '.', $_data['value'])) ?>" />
                    <?php endif;?>
                    </td>
                </tr>
            <?php endforeach; if ($weight >= 0.05) :?>
                <tr>
                    <th class="col label" scope="row">Fraktvikt</th>
                    <td class="col data" data-th="Fraktvikt" itemprop="weight" itemscope itemtype="http://schema.org/QuantitativeValue"><?=
                            number_format($weight, 1, ',', ' ') ?> <span itemprop="unitText">kg</span>
                        <meta itemprop="value" content="<?= (float)$weight ?>" />
                        <meta itemprop="unitCode" content="KGM" />
                    </td>
                </tr>
            <?php endif;?>
            </tbody>
        </table>
    </div>
<?php endif;?>
