<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Catalog\Block\Product\View\Details $block */
?>
<?php if ($detailedInfoGroup = $block->getGroupSortedChildNames('detailed_info', 'getChildHtml')) :?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout();
            $itemsEmpty = true;
            foreach ($detailedInfoGroup as $name) :
                $html = $layout->renderElement($name);
                if (!trim($html)) {
                    continue;
                }
                if ($itemsEmpty) :
        ?>
        <div class="product data items">
            <?php $itemsEmpty = false;
                endif;
                $alias = $layout->getElementAlias($name);
                $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data item content"
                     id="<?= $block->escapeHtmlAttr($alias) ?>">
                    <?= /* @noEscape */ $html ?>
                </div>
        <?php endforeach;
        if (!$itemsEmpty) :?>
        </div>
        <?php endif; ?>
    </div>
<?php endif; ?>
